### ISSUE TITLE
AR: add model flag menu

### ISSUE THREAD

**Issue by joz-f** [theodi/firetruck#37]
Add flag list as a modal so users can select their country to load into the arrivals board.

Text is yellow - and should go white on select and rollover

![20201102Artboard 1-80](https://user-images.githubusercontent.com/1784280/97924641-e407aa80-1d57-11eb-804d-43b83d67d501.jpg)

**Comment by stephendwolff** [comment]
country language showing, and arrivals board showing correct three countries and times.

**Comment by joz-f** [comment]
This looks great! I had some issues with the wrong language showing until after the first minute but I am wondering if this is linked with the GitHub pages update (or not).

**Comment by joz-f** [comment]
Done and working
