### ISSUE TITLE
BR: videos not autoplaying on Gee's laptop

### ISSUE THREAD

**Issue by joz-f** [theodi/firetruck#42]
Gee feedback: "videos don't launch automatically on my laptop. I have to click on YouTube screen in order for them to play."

I have asked him to let me know what browser and system he's using.

**Comment by stephendwolff** [comment]
I can't recreate this bug - let me know if you can and i'll look again.

**Comment by joz-f** [comment]
I can't either - i will ask for more tests

**Comment by joz-f** [comment]
Gee could not recreate, working fine.
