### ISSUE TITLE
LL: some issues with reload after the first poem.

### ISSUE THREAD

**Issue by joz-f** [theodi/firetruck#43]
Gee says "In the "Lost Luggage" section, I love the way that the 4 avatars of the recited verses light up. But I find that once the first audio read-through is over & it says "Tap again", I tap the screen and the new combination loads up onto the screen, but no sound is heard nor do any other avatars light up. So it seems to work perfectly the first time but the glitches occur when I try to request another configuration."

I wonder if it's the GitHub Pages serving things slowly or in a weird order>?

**Comment by stephendwolff** [comment]
i think this happens when someone double clicks, so i'll try and fix...

**Comment by stephendwolff** [comment]
OK i've pushed a fix. Will this automagically appear on the odi subdomain?

**Comment by joz-f** [comment]
I don't know - the html gets updated straight away, but does the JS need compiling? @rachelwilson can you answer this? If Stephen updates the source files does GitHub pages set-up auto compile?

**Comment by stephendwolff** [comment]
@joz-f and @rachelwilson i'm checking in the compiled code which lands in public_html/dist, so if the git repo is just pulled, it should 'just work'...

**Comment by joz-f** [comment]
This is the sequence that isn't quite right:

I click on Welsh in the modal and the poem loads straight away but the Remarks in red say Landing in Welsh at xx.xx (but the text has already landed)
![Screen Shot 2020-11-05 at 15 43 19](https://user-images.githubusercontent.com/1784280/98273439-2adce680-1f8a-11eb-87af-f947c409dbcd.jpg)
Then I clicked Madrid, and the Spanish poem loads but the Remarks in red still say Landing in Welsh at xx.xx
![Screen Shot 2020-11-05 at 15 43 32](https://user-images.githubusercontent.com/1784280/98273445-2dd7d700-1f8a-11eb-8df8-82dee877ca7b.jpg)
Then at 40 seconds past the minute the Remark in red updated to Landing in Spanish at xx.xx even though the Spanish poem was loaded
![Screen Shot 2020-11-05 at 15 43 43](https://user-images.githubusercontent.com/1784280/98273448-2e706d80-1f8a-11eb-9dd8-d93bb2e846d1.jpg)
Then I waited for the time to arrive (15:44) and the text didn't change it still said Landing in Spanish at xx.xx
![Screen Shot 2020-11-05 at 15 44 10](https://user-images.githubusercontent.com/1784280/98273451-2f090400-1f8a-11eb-9731-66178ebcceb9.jpg)

**Comment by joz-f** [comment]
font changed and reload now speedy
